### ISSUE TITLE
No information displayed in unsupported browsers

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-onboarding#16]
https://onboarding-dev.trezor.io/
no device needed
Safari, Opera, Edge

No information is displayed in unsupported browsers - page gets stuck on the loading animation.
![Peek 2019-04-08 13-30](https://user-images.githubusercontent.com/10185314/55721006-876cce00-5a02-11e9-907c-84625d10fedc.gif)

**Comment by mroz22** [comment]
For IE <= 9 should be fixed in https://github.com/trezor/trezor-onboarding/commit/e4c1ad44d372bc7b9b59c961011a99457309f041

**Comment by mroz22** [comment]
Please check again @sorooris and close if solved.

**Comment by sorooris** [comment]
Retest NOK, issue still persists. None of the unsupported browsers display info about being unsupported.
